workflows:
  android-debug:
    name: CineZo+ Android
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: v20
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Instalar dependencias
        script: |
          npm install
      - name: Adicionar Android
        script: |
          ./node_modules/.bin/cap add android || true
      - name: Sincronizar
        script: |
          ./node_modules/.bin/cap sync
      - name: Gerar APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
